# Generated by Django 6.0.4 on 2026-05-11 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitoBooleano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-nombre'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HabitoContador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('objetivo_diario', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['-nombre'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HabitoSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('objetivo_semanal', models.IntegerField(default=3)),
            ],
            options={
                'ordering': ['-nombre'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cumplido', models.BooleanField(default=False)),
                ('valor', models.FloatField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('habito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='habitos.habitobooleano')),
                ('habito_contador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='habitos.habitocontador')),
                ('habito_semanal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='habitos.habitosemanal')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
