# Generated by Django 6.0.4 on 2026-05-18 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habitos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='habito',
            new_name='habito_booleano',
        ),
    ]
